* mgl-pax                                                     :documentation:
:PROPERTIES:
:Documentation: :)
:Docstrings: :)
:Tests:    :)
:Examples: :)
:RepositoryActivity: :)
:CI:       :(
:END:

This is a very cool documentation generator for Common Lisp projects.


The most interesting features are:

- Emacs/SLIME integration.
- Ability to generate Markdown.
- API to add new entity types.
- Linking to the sources on the GitHub.
- Docstrings deindentation.
- Generation docs for multiple ASDF systems with cross-referencing.
- Auto-export of documented symbols.

Some cons:

- The recommended way to mix documentation section with code leads to
  the runtime dependency from PAX and all it's dependencies. But you
  might define documentation as a separate ASDF system.
- It is inconvenient to write Markdown in docstrings. Is there any way
  to teach Emacs to use markdown minor mode for documentation strings?

There are more pros and cons. All of them are listed in the
[[https://cl-doc-systems.github.io/mgl-pax/#x-28EXAMPLE-DOCS-2FDOCS-3A-40PROS-N-CONS-20MGL-PAX-3ASECTION-29][example project]]. It is up and ready to be cloned. Use it as a template
for your own Common Lisp library with great documentation!

You'll find all such templates in this GitHub organization:

https://github.com/cl-doc-systems

I have plans to review a few other documentation builders, but MGL-PAX
is my favourite so far.
