* declt                                                       :documentation:
:PROPERTIES:
:Documentation: :)
:Docstrings: :)
:Tests:    :(
:Examples: :(
:RepositoryActivity: :)
:CI:       :(
:License:  BSD
:HomePage: https://github.com/didierverna/declt
:END:

This is the documentation builder behind [[https://quickref.common-lisp.net/][Quickref]] site. It is good for
generating API references for third party libraries.

Most interesting features of Quickref are:

- ~Declt~ uses [[https://www.gnu.org/software/texinfo/manual/texinfo/texinfo.html][Texinfo file format]] for intermediate document store.
  This makes posssible to generate not only HTML, but also PDF and other
  output formats.
- It can automatically include license text into the documentation. But
  this works only for a number of popular licenses like MIT

As always, I've created a template project, ready to be used:

https://github.com/cl-doc-systems/declt

Here is how it is rendered in HTML:

https://cl-doc-systems.github.io/declt/

And in PDF:

https://cl-doc-systems.github.io/declt/index.pdf

Sadly, ~Declt~ does not support markup in docstrings and cross-referencing
does not work there.

Some other pros and cons are listed on [[https://cl-doc-systems.github.io/declt/#Pros-_0026-Cons][example site]].

Remember, all example projects from https://github.com/cl-doc-systems
include a build script and GitHub Action to update documentation on
every commit!

